### ISSUE TITLE
有上架 appstore 的计划么

### ISSUE THREAD

**Issue by MechanE** [AlanLang/BitClient#10]
大佬有上架 app store 的计划么？感觉目前 ios 端缺少 qb 的管理工具

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by AlanLang** [comment]
暂时可能没有，现在主要是自用，专门为了这一个 app 去订阅苹果开发者有点亏，也没打算过在这上面盈利。

**Comment by bonny1992** [comment]
Sorry to "barge in" but (at least if nothing has changed) Apple must have something specifically against torrent management apps.
There's LunaSea (https://apps.apple.com/gb/app/lunasea/id1496797802) that (if I'm not wrong) wanted to add support for torrent clients but Apple refused.
Usenet apparently is over this, I don't really know why.

**Comment by AlanLang** [comment]
> Sorry to "barge in" but (at least if nothing has changed) Apple must have something specifically against torrent management apps. There's LunaSea (https://apps.apple.com/gb/app/lunasea/id1496797802) that (if I'm not wrong) wanted to add support for torrent clients but Apple refused. Usenet apparently is over this, I don't really know why.

Apple may consider this to be a potential copyright issue.
