### ISSUE TITLE
Translation in English

### ISSUE THREAD

**Issue by bonny1992** [AlanLang/BitClient#12]
Heya!
This feels like the most polished and well done app to control qbittorrent when using iOS.

Is a translation in other languages (for example, English) in your plans?

I saw this translation: https://github.com/AlanLang/BitClient/blob/main/BitClient/Resources/Localization/Constants/en.lproj/Constants_Localizable.strings
But can't find how to use English in the app, if it's possible, of course.

**Comment by bonny1992** [comment]
Sorry if I said something "strange" but I'm not an Apple dev...
I'm gonna also tag @swift2geek because I saw that the commits where theirs.

**Comment by AlanLang** [comment]
Yes, we now have the English internationalization files, but it seems that they are not automatically switching based on the system settings. This is a bug, and I will fix it. Thank you for bringing it to my attention.

**Comment by AlanLang** [comment]
You can temporarily install this app, as I have set the default language to English. I will first investigate how to automatically switch based on the system language. I apologize, as I am not an iOS developer myself.
https://github.com/AlanLang/BitClient/releases/download/v1.2.1/BitClient-en.ipa

**Comment by AlanLang** [comment]
Now you can install the latest version (v1.2.2) of the app. In this version, I have fixed the internationalization issue.

**Comment by bonny1992** [comment]
That was fast :D
Thank you!
I've tried installing a VM with MacOS to build it myself but I loudly failed :D

**Comment by bonny1992** [comment]
> Now you can install the latest version (v1.2.2) of the app. In this version, I have fixed the internationalization issue.

Oh only one thing:
I believe if the phone isn't set in English as the main language, it won't switch to it automatically.
Might want to make the user choose, maybe at login?

**Comment by AlanLang** [comment]
Very good suggestion, but I think it's most intuitive to use the language of the system settings, and I don't understand why users would want to use a different language than their own system settings.

**Comment by AlanLang** [comment]
> > Now you can install the latest version (v1.2.2) of the app. In this version, I have fixed the internationalization issue.
> 
> Oh only one thing: I believe if the phone isn't set in English as the main language, it won't switch to it automatically. Might want to make the user choose, maybe at login?
> 
> EDIT: Sadly this one https://github.com/AlanLang/BitClient/releases/download/v1.2.1/BitClient-en.ipa is still in Chinese. Tried deleting the app and installing it and installing it in place of the previous one, no luck.

Is version v1.2.2 useful for you?

**Comment by bonny1992** [comment]
> Very good suggestion, but I think it's most intuitive to use the language of the system settings, and I don't understand why users would want to use a different language than their own system settings.

I agree with you, but maybe just as a workaround?



> Is version v1.2.2 useful for you?

![FullSizeRender-2](https://github.com/AlanLang/BitClient/assets/1154368/32943d2e-7d23-4a63-9ac7-aab148f24a4e)

Sadly not.
This is a screenshot from 1.2.2, directly after uninstalling the app and reinstalling it.
My phone is set in Italian, maybe that's why? I don't really know how this works underneath.

**Comment by AlanLang** [comment]
I see. Since I have set the default language to Chinese if no language package is available, you can go to the system settings and put English as the second option.
![IMG_DE0FF803EA5B-1](https://github.com/AlanLang/BitClient/assets/33884749/00e7cd2a-6597-437f-9853-f870e54f3d17)

**Comment by AlanLang** [comment]
If this issue is resolved, I will close it.

**Comment by bonny1992** [comment]
Just as a small report though, there's still _some_ strings not yet translated in English.
The toasts notifications and the "delete" submenu, for example.

**Comment by AlanLang** [comment]
Okay, I will provide the translation for the remaining text later.
