### ISSUE TITLE
Fields in login are white text on white box

### ISSUE THREAD

**Issue by bonny1992** [AlanLang/BitClient#13]
I believe this is because the phone is set with the dark theme?

![FullSizeRender](https://github.com/AlanLang/BitClient/assets/1154368/49e57ddc-b29d-46fe-8bdc-e8c4805709f8)

(not related to version, 1,2.1 and 1.2.2 behaves the same)

**Comment by AlanLang** [comment]
Yes, there is a slight issue with the display of BitClient in dark theme. I will fix it later.

**Comment by swift2geek** [comment]
[this](https://github.com/AlanLang/BitClient/pull/15/files) should solve the issue.
