### ISSUE TITLE
ios14恳请兼容

### ISSUE THREAD

**Issue by LK373391947** [AlanLang/BitClient#16]
大佬你好，我的手机由于想保留越狱一直处于ios14.6，能否兼容一下，谢谢🙏

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by AlanLang** [comment]
非常抱歉，不太好兼容，因为里面好多内容都用到了 iOS 15.0 的特性。
