### ISSUE TITLE
哪位大佬出一期安装教程?

### ISSUE THREAD

**Issue by Leevisonline** [AlanLang/BitClient#19]
系统版本16.3.1

**Comment by Leevisonline** [comment]
![image](https://github.com/AlanLang/BitClient/assets/147957330/374e9933-9633-466a-bbfa-ade71d3fdcfd)

**Comment by Leevisonline** [comment]
你好远程服务器这里如何填写？我在浏览器打开网址是正确的！

**Comment by AlanLang** [comment]
> 你好远程服务器这里如何填写？我在浏览器打开网址是正确的！

你好，这个 APP 只支持 qBittorrent 的

**Comment by Leevisonline** [comment]
> > 你好远程服务器这里如何填写？我在浏览器打开网址是正确的！
> 
> 
> 
> 你好，这个 APP 只支持 qBittorrent 的

![image](https://github.com/AlanLang/BitClient/assets/147957330/8479e8c6-4972-4572-8f7c-87e7d9abfe9f)

**Comment by Leevisonline** [comment]
> > 你好远程服务器这里如何填写？我在浏览器打开网址是正确的！
> 
> 
> 
> 你好，这个 APP 只支持 qBittorrent 的

![image](https://github.com/AlanLang/BitClient/assets/147957330/7b5b0e15-b812-4452-a791-0bedaa1e89e0)

**Comment by Leevisonline** [comment]
QB也无法登陆呢！自签证书安装的！

**Comment by AlanLang** [comment]
> QB也无法登陆呢！自签证书安装的！
前面的 http:// 也需要有

**Comment by AlanLang** [comment]
你好，怎么样了，有最新进展吗？

**Comment by Leevisonline** [comment]
不行！无法使用！不能联网！
