### ISSUE TITLE
app联网权限问题

### ISSUE THREAD

**Issue by ChrisShen-github** [AlanLang/BitClient#4]
大佬，我安装好了app，打开以后没有提示允许此软件使用wlan或者蜂窝数据，导致app连不上网，设置中也找不到这个app，反复重启app也没有允许联网权限的弹框，死活连不上网

**Comment by AlanLang** [comment]
我在设置中是可以找到这个 app 的，不应该没有呀，再仔细找找呢？

**Comment by ChrisShen-github** [comment]
找了好久呢，大佬你看b开头的![image](https://user-images.githubusercontent.com/37608623/195082492-8af63589-5153-407a-b377-cb3dcb6cadc7.png)![image](https://user-images.githubusercontent.com/37608623/195082556-a0fd50dd-69cb-4b83-83e1-a69abe6c889e.png)

**Comment by ChrisShen-github** [comment]
找了好久呢，还是没找到，大佬你看b开头的就一个![image](https://user-images.githubusercontent.com/37608623/195082693-c4eb9525-bd62-43a2-8b52-f4fd919f8e1a.png)![image](https://user-images.githubusercontent.com/37608623/195082739-8e4bf4e0-17eb-437b-844a-3a34534d0270.png)

**Comment by ChrisShen-github** [comment]
> 我在设置中是可以找到这个 app 的，不应该没有呀，再仔细找找呢？

找了好久呢，还是没找到😔，大佬你看b开头的就一个![image](https://user-images.githubusercontent.com/37608623/195082893-ed6d6d73-59d7-41ed-a79e-2dd846d8838d.png)![image](https://user-images.githubusercontent.com/37608623/195082899-52b8c680-30ef-401d-874d-189a1696c2de.png)

**Comment by ChrisShen-github** [comment]
> 我在设置中是可以找到这个 app 的，不应该没有呀，再仔细找找呢？

找了好久呢，还是没找到，大佬你看b开头的就一个![image](https://user-images.githubusercontent.com/37608623/195083177-3410b4a7-060e-4a6b-b5c4-a19a67ffb851.png)![image](https://user-images.githubusercontent.com/37608623/195083183-0f8833da-d902-4025-9f92-946744114627.png)

**Comment by AlanLang** [comment]
哦哦，我没有在AltStore上安装测试过，平时都是自签名安装的，有时间我用AltStore安装试试。

**Comment by ChrisShen-github** [comment]
> 哦哦，我没有在AltStore上安装测试过，平时都是自签名安装的，有时间我用AltStore安装试试。

好的好的😁

**Comment by FanxJK** [comment]
在`Info.plist`中添加`NSAllowsArbitraryLoads`键允许应用加载任意URL，`NSAllowsLocalNetworking`键允许应用访问本地网络即可

**Comment by AlanLang** [comment]
> 在`Info.plist`中添加`NSAllowsArbitraryLoads`键允许应用加载任意URL，`NSAllowsLocalNetworking`键允许应用访问本地网络即可

感谢，我修改下试一试

**Comment by AlanLang** [comment]
我确认了一下，确实通过 [AltStore](https://altstore.io/) 安装，在设置菜单里找不到。
