### ISSUE TITLE
希望可与添加标签功能

### ISSUE THREAD

**Issue by LK373391947** [AlanLang/BitClient#5]
首先感觉这个app非常好用，功能简单，界面简洁易配置
希望作者可以添加标签和分类功能便于整理下载的文件

**Comment by AlanLang** [comment]
感谢建议，本来这个手机端app没有想做太多复杂的功能，复杂操作最好还是直接通过电脑来做更为快捷。
你提的建议非常好，待我想好该怎么设计交互后会把功能实现上去的。
